name: pliatsikas_app
description: >
  A comprehensive Flutter application for managing orders at Pliatsikas Chicken business,
  featuring order creation, customer management, and delivery scheduling.
version: 1.0.2+2
homepage: https://github.com/LoukasAvgerinos/Pliatsikas-App
repository: https://github.com/LoukasAvgerinos/Pliatsikas-App
issue_tracker: https://github.com/LoukasAvgerinos/Pliatsikas-App/issues

publish_to: 'none'

environment:
  sdk: '>=3.6.1 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  sqflite: ^2.4.1
  path: ^1.9.0
  shared_preferences: ^2.5.1
  uuid: ^4.5.1
  lottie: ^3.3.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.jpeg
    - assets/images/pliatsikas_image_app.png
    - assets/json/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/pliatsikas_image_app.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/pliatsikas_image_app.png"
